# Request message types
string turtle_name # Name of the turtle
float32 vel     # Linear velocity   
float32 omega   # Angular velocity
float32 x       # X coordinate (initial pos)
float32 y       # Y coordinate (initial pos)
float32 theta   # Orientation (initial pos)
---
# Response message types
geometry_msgs/Twist cmd  # Response is the velocity command
